name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: AppThreat/sast-scan-action@v1.0.0
        with:
          type: "nodejs"

      - uses: actions/upload-artifact@v1.0.0
        with:
          name: reports
          path: reports
